In [2]:
import pandas as pd
import pm4py

In [18]:
application_event_log = pm4py.read_xes('../data/application_data.xes')
offer_event_log = pm4py.read_xes('../data/offer_data.xes')

parsing log, completed traces :: 100%|██████████| 31509/31509 [00:46<00:00, 680.69it/s]
parsing log, completed traces :: 100%|██████████| 42995/42995 [00:05<00:00, 7401.56it/s]

In [16]:
pm4py.get_end_activities(application_event_log)

{'W_Validate application': 12662,
 'O_Cancelled': 4436,
 'W_Call after offers': 9457,
 'W_Call incomplete files': 4676,
 'W_Complete application': 144,
 'W_Assess potential fraud': 102,
 'W_Personal Loan collection': 2,
 'W_Shortened completion ': 5,
 'A_Denied': 1,
 'O_Sent (online only)': 8,
 'O_Sent (mail and online)': 15,
 'O_Returned': 1}

In [19]:
pm4py.get_end_activities(offer_event_log)

{'O_Cancelled': 20898,
 'O_Accepted': 17228,
 'O_Refused': 4695,
 'O_Returned': 49,
 'O_Sent (mail and online)': 108,
 'O_Sent (online only)': 17}

In [21]:
df_offer = pm4py.convert_to_dataframe(offer_event_log)
df_offer['concept:name'].value_counts()

O_Create Offer              42995
O_Created                   42995
O_Sent (mail and online)    39707
O_Returned                  23305
O_Cancelled                 20898
O_Accepted                  17228
O_Refused                    4695
O_Sent (online only)         2026
Name: concept:name, dtype: int64

In [24]:
df_application = pm4py.convert_to_dataframe(application_event_log)

,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,case:ApplicationType,case:concept:name,case:RequestedAmount,FirstWithdrawalAmount,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID
0,Created,User_1,A_Create Application,Application,Application_652823628,complete,2016-01-01 09:51:15.304000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,statechange,User_1,A_Submitted,Application,ApplState_1582051990,complete,2016-01-01 09:51:15.352000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Created,User_1,W_Handle leads,Workflow,Workitem_1298499574,schedule,2016-01-01 09:51:15.774000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Deleted,User_1,W_Handle leads,Workflow,Workitem_1673366067,withdraw,2016-01-01 09:52:36.392000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Created,User_1,W_Complete application,Workflow,Workitem_1493664571,schedule,2016-01-01 09:52:36.403000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202262,Deleted,User_1,W_Call after offers,Workflow,Workitem_1817549786,ate_abort,2017-01-06 06:33:02.212000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202263,Created,User_1,W_Call after offers,Workflow,Workitem_363876066,schedule,2017-01-06 06:33:02.221000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202264,statechange,User_28,A_Cancelled,Application,ApplState_1869071797,complete,2017-01-16 09:51:21.114000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202265,statechange,User_28,O_Cancelled,Offer,OfferState_420066181,complete,2017-01-16 09:51:21.139000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Offer_1580299144
1202266,Deleted,User_28,W_Call after offers,Workflow,Workitem_1934044935,withdraw,2017-01-16 09:51:21.146000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df_application.groupby(['case:concept:name', 'concept:name']).size().unstack().reset_index().columns

Index(['case:concept:name', 'A_Accepted', 'A_Cancelled', 'A_Complete',
       'A_Concept', 'A_Create Application', 'A_Denied', 'A_Incomplete',
       'A_Pending', 'A_Submitted', 'A_Validating', 'O_Accepted', 'O_Cancelled',
       'O_Create Offer', 'O_Created', 'O_Refused', 'O_Returned',
       'O_Sent (mail and online)', 'O_Sent (online only)',
       'W_Assess potential fraud', 'W_Call after offers',
       'W_Call incomplete files', 'W_Complete application', 'W_Handle leads',
       'W_Personal Loan collection', 'W_Shortened completion ',
       'W_Validate application'],
      dtype='object', name='concept:name')

In [50]:
df_offer.groupby(['case:concept:name', 'concept:name']).size().unstack().reset_index().columns

Index(['case:concept:name', 'O_Accepted', 'O_Cancelled', 'O_Create Offer',
       'O_Created', 'O_Refused', 'O_Returned', 'O_Sent (mail and online)',
       'O_Sent (online only)'],
      dtype='object', name='concept:name')

In [15]:
# from https://pm4py.fit.fraunhofer.de/documentation#item-7-0-1 
from pm4py.algo.transformation.log_to_features import algorithm as log_to_features

data, feature_names = log_to_features.apply(event_log)
df = pd.DataFrame(data, columns=feature_names)
df

,trace:ApplicationType@Limit raise,trace:ApplicationType@New credit,event:case:ApplicationType@Limit raise,event:case:ApplicationType@New credit,event:EventOrigin@Application,event:EventOrigin@Offer,event:EventOrigin@Workflow,event:Action@Created,event:Action@Deleted,event:Action@Obtained,...,succession:concept:name@W_Validate application#O_Accepted,succession:concept:name@W_Validate application#O_Cancelled,succession:concept:name@W_Validate application#O_Create Offer,succession:concept:name@W_Validate application#O_Returned,succession:concept:name@W_Validate application#O_Sent (online only),succession:concept:name@W_Validate application#W_Assess potential fraud,succession:concept:name@W_Validate application#W_Call incomplete files,succession:concept:name@W_Validate application#W_Personal Loan collection,succession:concept:name@W_Validate application#W_Shortened completion,succession:concept:name@W_Validate application#W_Validate application
0,0,1,0,1,1,1,1,1,1,1,...,1,0,0,0,0,0,1,0,0,1
1,0,1,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,1
2,0,1,0,1,1,1,1,1,1,1,...,1,0,0,0,0,0,1,0,0,1
3,0,1,0,1,1,1,1,1,1,1,...,1,1,0,0,0,0,1,0,0,1
4,0,1,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31504,0,1,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,1
31505,0,1,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
31506,0,1,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,1
31507,0,1,0,1,1,1,1,1,1,1,...,1,0,0,0,0,0,1,0,0,1
31508,0,1,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0